import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link"; // Link import is not used here anymore, but Header uses it.
import "./globals.css";
import Header from "@/components/Header"; // Import the Header component

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Gemini",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Header /> {/* Use the Header component */}
				<main className="container mx-auto p-4">
					{children}
				</main>
			</body>
		</html>
	);
}
